# Site settings
title: Sukrit Gulati
description: Sukrit Gulati
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sukrit Gulati
user_description: Mobile Development 
user_title: Software Developer, Mobile Developer
email: sukritgulati@gmail.com
twitter_username: gulatisukrit
linkedin_username: sukritgulati
github_username:  sukritgulati
instagram_username: sukritgulati


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
